version: 0.2

env:
  variables:
    SLS_DEBUG: 1

phases:
  install:
    runtime-versions:
        nodejs: 14
        dotnet: 3.1
    commands:
      - echo Installing...
      - dotnet tool install -g Amazon.Lambda.Tools --framework netcoreapp3.1
      - npm ci
  build:
    commands:
      - echo Building...
      - make build
  post_build:
    commands:
      - echo Post-build...
      - echo Running unit tests place holder...
      - echo Running integration tests place holder...

artifacts:
  files:
    - 'dotnet-lambdas/bin/Release/netcoreapp3.1/package.zip'
    - 'dotnet-lambdas/appspec.yaml'
    - 'dotnet-lambdas/deployspec.yaml'
    - 'package-lock.json'
    - 'package.json'
    - 'serverless.yml'
  name: bk-dotnet-lambdas-artifact-demo-$(date +%Y-%m-%d)
